README.md, src/decoder.js, src/signer.js, src/verifier.js, test/decoder.spec.js, test/signer.spec.js, test/verifier.spec.js
The JWT spec mandates that the payloads MUST be objects (#33) 
From: https://tools.ietf.org/html/rfc7519#section-7.2
> 10. Verify that the resulting octet sequence is a UTF-8-encoded
> representation of a completely valid JSON object conforming to
> RFC 7159 [RFC7159]; let the JWT Claims Set be this JSON object.
- adjusted the decoder, signer and verifier to make sure that the payloads are only of type object.
- adjusted the tests to reflect the changes
- updated the docs
=> Payloads only objects

package.json, src/verifier.js, test/crypto.spec.js
Makes some adjustments in code and tests to get full test coverage.
From issue #32 
- test `detectPublicKeyAlgorithms` output `none`
- remove duplicate check on `allowedAlgorithms` in `validateAlgorithmAndSignature`. this is a private function that's been called from `createVerifier` where the same check has already been done, causing this code never to be hit.
- force full code test coverage
=> Adjustments to get full test coverage

src/signer.js, test/signer.spec.js
The payload options provided by `createSigner` should overwrite the ones in the payload that needs to be signed.
But when the options are **not** provided to the `createSigner` function, they are always `undefined` when property merge occurs. This overwrites the properties of the payload provided in `sign` with empty values as in issue #38 . 
This changes clears the `fixedProperties` from empty values before merging.
=> Removes undefined props

README.md, src/decoder.js, src/signer.js, src/verifier.js, test/decoder.spec.js, test/verifier.spec.js
This change makes it possible to skip the `typ` check on the decoded header.
According to the JWT specs, a header with typ JWT is always expected, but in case of AWS Cognito, this property is not available. `skipTypCheck` on the decoder works around this.
=> Header typ check

src/signer.js, test/signer.spec.js
Add support for a custom exp claim in the payload (Issue #58)
```javascript
const signSync = createSigner({ key: 'secret' })
const token = signSync({
a: 1,
exp: Math.floor(Date.now() / 1000) + (60 * 60 * 2),
})
```
I kept the behavior of overwriting "exp" if the option "expiresIn" is set.
Should I add any more validations or tests, or change some behavior?
Thanks
=> feat: Add support for exp claim in the payload

src/verifier.js, test/verifier.spec.js
This PR fixes a bug where allow `allowed*` options in the `createVerifier` were mistakenly converted to Regexp when specified as strings.
This leads to accept a claim that just contained the allowed ones. For instance:
```javascript
const { createSigner } = require('fast-jwt')
const { createVerifier } = require('fast-jwt')
const signSync = createSigner({ key: 'secret' })
const verifySync = createVerifier({ key: 'secret', allowedIss: 'ISS' })
// The following should throw, but it currently does not
const payload = verifySync(signSync({iss: 'FOO_ISS_BAR`}))
```
The solution is to use equality check rather than regexp testing.
=> fix: Fixed allowed claims verification.

.npmignore, package.json
PR https://github.com/nearform/fast-jwt/pull/69 inadvertently caused coverage files to be included in the published package.  This PR adds `test`, `nyc_output`, and `coverage` directories to `.npmignore` in order to fix it.
=> chore: add files field to package.json

README.md
Hello.
Update the `mutatePayload` related documentation.
=> refactor (docs): fix `mutatePayload` definition sentence

README.md
Hello.
This PR aims to improve the documentation of `fast-jwt` by:
- properly documenting options and with direct RFC reference links (all relevant JWT related documentation accessible from one place),
- some sentence rephrasing,
- some formatting to enhance the reading experience (adding some white space between the options listing makes it easy to focus on the wanted information).
=> refactor (docs): Improve documentation

src/verifier.js, test/verifier.spec.js
Refactored `checkAreCompatibleAlgorithms` function  to take into account all of the algorithms supplied in the options as allowed algorithms.
Closes #157
=> Refactoring checkAreCompatibleAlgorithms function 

src/index.d.ts, test/types.spec.ts
Right now types define Signer and Verifier as either Promise or a
callback function; however looking at the examples in README and
code [0], this is true only if `key` is a function.
So changing the types a bit here to reflect reality.
[0] https://github.com/nearform/fast-jwt/blob/c239279dfe6a086a68132b05a5c729fe11352602/src/signer.js#L303
=> Distinguish between sync & async methods in types

README.md, src/error.js, src/verifier.js, test/verifier.spec.js
Introduces a new option, `requiredClaims`, to the verifier, which will check in the token for the presence of a set of claims.
Note that no claim is required by default, this way preserving the current behavior of skipping undefined claims even when an `allowed*` option is used.
Closes #182
=> Introduce `requiredClaims` option to the verifier

benchmarks/auth0.mjs, benchmarks/decode.mjs, benchmarks/sign.mjs, benchmarks/utils.mjs, benchmarks/verify.mjs, package.json
This PR converts the benchmark CommonJS modules into ES modules so we can use `cronometro` properly.
Closes #185
=> fix benchmarks

README.md, src/verifier.js, test/verifier.spec.js
This should fix #192,
The `clockTolerance` property in `createVerifier` options will now be tolerant on both `nbf`  and `exp` token properties.
The modification should keep the exact same behavior with `maxAge` and `cacheTTL`.
=> fix: clockTolerance property in verifier

src/verifier.js, test/verifier.spec.js
Fix #194 
I tried to fix the behavior without changing too much lines, but the result isn't that easy to read.
Also I'm not sure if using the `FAST_JWT_INACTIVE` code here is the way to go...
=> Fix cache containing "not yet active tokens"  that never become active 

src/index.d.ts
Fix #217 
this fix typings when using passphrase protected private key on `createSigner`
=> fix: missing types - `createSigner` private key

src/signer.js, test/signer.spec.js
closes #254 
- Changed priority of payload exp claim in signer
- Updated test to check for payload exp claim priority over expiresIn config value
=> Prioritise payload exp claim #254

src/index.d.ts
According to the [README](https://github.com/nearform/fast-jwt/blob/master/README.md#createsigner), the signer options allows the `aud` option to be an array of strings. However, the corresponding TypeScript typing does not allow the property to be an array of strings. This PR fixes the typing error.
This PR fixes #262.
=> fix: `aud` in SignerOptions should accept array of strings

.github/workflows/release.yml
Change optic-release-automation-action version to test version to debug issue where release draft is not being created
=> Change release action for testing

.gitignore, src/signer.js
With this PR I would like to remove all the slow `.includes` checks in favour of a single `Set.has` method, which should be faster.
Additionally, I'm modifying `Object.keys` to `Object.entries` in order to avoid extracting the value multiple times.
Here are the benchmarks:
- BEFORE
```
╔══════════════════════════════╤═════════╤═════════════════╤═══════════╤═════════════════════════╗
║ Slower tests                 │ Samples │          Result │ Tolerance │ Difference with slowest ║
╟──────────────────────────────┼─────────┼─────────────────┼───────────┼─────────────────────────╢
║ HS512 - jsonwebtoken (async) │    1500 │  1512.00 op/sec │  ± 0.72 % │                         ║
║ HS512 - jsonwebtoken (sync)  │    1000 │  1591.16 op/sec │  ± 0.36 % │ + 5.24 %                ║
║ HS512 - jose …
```
=> chore: use set to check supported algorithms

src/index.d.ts, src/signer.js, src/utils.js, src/verifier.js, test/signer.spec.js, test/types.spec.ts, test/verifier.spec.js
This PR enables receiving the whole JWT object for the key callback instead of only the headers. 
Close #330.
=> feat!: provide fully decoded jwt object to key callback

benchmarks/utils.mjs, package.json
Additional tool in the benchmark, this time for the sign operation.
This has been added to demonstrate the speed of [napi-rs](https://napi.rs/).
```
╔═══════════════════════════════════════╤═════════╤══════════════════╤═══════════╤═════════════════════════╗
║ Slower tests                          │ Samples │           Result │ Tolerance │ Difference with slowest ║
╟───────────────────────────────────────┼─────────┼──────────────────┼───────────┼─────────────────────────╢
║ HS512 - jsonwebtoken (async)          │    1000 │   3643.83 op/sec │  ± 0.30 % │                         ║
║ HS512 - jsonwebtoken (sync)           │    1000 │   3663.59 op/sec │  ± 0.44 % │ + 0.54 %                ║
║ HS512 - @node-rs/jsonwebtoken (async) │    2000 │  84971.86 op/sec │  ± 0.95 % │ + 2231.94 % …
```
=> feat: additional tool in sign benchmark

src/index.d.ts
jsonwebtoken has all these fields optional, would make sense to make these fields optional here as well
=> Make fields of signerOptions and verifierOptions optional

README.md, package.json, src/signer.js, test/signer.spec.js
Closes #363 
uses https://github.com/lukeed/ms underneath
Had to adjust the tests, update the docs and implement the ms lib
=> support notBefore and expiresIn as strings

benchmarks/keys/generate-keys.js, benchmarks/keys/generate-tokens.js, src/crypto.js, src/signer.js, src/utils.js, src/verifier.js, test/compatibility.spec.js, test/crypto.spec.js, test/signer.spec.js, test/verifier.spec.js
Allows redundant `require.cache` calls to be bypassed for builtin modules, saving a few yoctoseconds.
See https://nodejs.org/api/modules.html#core-modules and [discussion in nodejs/node repo regarding why `require.cache` calls are redundant for builtins](https://github.com/nodejs/node/pull/37246/files#r588397158).
=> perf: use `node:` prefix to bypass require.cache call for builtins

src/index.d.ts, test/types.spec.ts
=> Allow expiresIn to be a string

package.json
Removed the pre-publish step to run tests, since the time delay caused by running these tests can cause the release to fail due to the optic token expiring. The repo needs to pass CI anyway for the release to be successful, so this step was unnecessary.
closes https://github.com/nearform/fast-jwt/issues/368
=> fix: removed pre publish step

src/index.d.ts, test/types.spec.ts
This better reflects the actual source implementation and fixes #402.
The unit test is somewhat brittle, since it's too trusting of the .d.ts types. I don't know how to overcome this limitation without just typing the whole project properly
=> fix: add missingRequiredClaim to TokenValidationErrorCode

src/index.d.ts, test/types.spec.ts
=> fix(typescript): fix typescript type DecodedJwt

src/verifier.js, test/verifier.spec.js
This PR ensures that custom claims are checked if they are specified in `requiredClaims`. Previously only a small subset of claims were validated.
Fixes #422
=> fix: Ensure required claims applies to custom claims

src/signer.js, test/sign-decode.spec.js, test/signer.spec.js
Use `nbf` claim if present on payload.
closes #453
=> `nbf` claim not used when passed on the payload (solve #453)

src/index.d.ts
Hi,
i was trying out @fastify/jwt in a new project. I have noticed my eslint rule "import/no-cycle" was failing,
because it can't resolve the import.
```
[Error - 23:34:21] EslintPluginImportResolveError: unable to load resolver "node".
Occurred while linting /app/src/plugins/auth/authorization.ts:2
Rule: "import/no-cycle"
at requireResolver (/app/node_modules/eslint-module-utils/resolve.js:201:17)
at fullResolve (/app/node_modules/eslint-module-utils/resolve.js:141:22)
at Function.relative (/app/node_modules/eslint-module-utils/resolve.js:158:10)
at remotePath (/app/node_modules/eslint-plugin-import/lib/ExportMap.js:811:381)
at captureDependency (/app/node_modules/eslint-plugin-import/lib/ExportMap.js:817:463)
at captureDependencyWithSpecifiers …
```
=> remove unnecessary import in declaration file

src/crypto.js, src/signer.js, src/verifier.js, test/compatibility.spec.js, test/compliance.spec.js, test/crypto.spec.js, test/signer.spec.js, test/verifier.spec.js
Now that we support just Node 20+, we can remove all the checks that relies on `useNewCrypto`
=> feat: deprecate use new crypto

src/verifier.js, test/verifier.spec.js
=> fix: return token as input property in verify when complete is true

src/index.d.ts, src/verifier.js, test/types.spec.ts, test/verifier.spec.js
This PR adds missing `input: string` field in `DecodedJwt` type.
Also fixed to return decoded input field rather than whole token.
Also, Updating types as per [comment]( https://github.com/nearform/fast-jwt/issues/521#issuecomment-2536672724)
Fixes: #521
=> chore(types): Add missing input type for DecodedJwt and Updated input field to return decoded 'input'

package.json, test/verifier.spec.js
- Remove sinon fake timer in favour of node tests one
=> chore: fake timer

src/index.d.ts, test/types.spec.ts
relates to #504 and #503
fixes #547
=> chore: add type for cacheKeyBuilder

src/verifier.js, test/verifier.spec.js
BREAKING CHANGE
Enhances the claim validation to match the JWT specification by ensuring that claim values are strings and not arrays
Resolves https://github.com/nearform/fast-jwt/issues/552
=> feat!: align claim validation to specification

src/signer.js, test/signer.spec.js, test/verifier.spec.js
Supports negative `expiresIn` option when signing tokens
Resolves #555
=> feature: support negative expiresIn when signing tokens

README.md
Adds a new "Error Handling" section to the README.md.
This section explains how to catch `TokenError` exceptions and inspect the `code` property to determine the specific error. It includes code examples for handling:
- Expired tokens (`FAST_JWT_EXPIRED`)
- Invalid signatures due to key mismatch (`FAST_JWT_INVALID_SIGNATURE`)
Resolves #560 by providing documentation on how to handle common token verification errors.
=> docs: Add error handling section with examples
